---
version: '3.8'
volumes:
  jackett_config: {}
  redis_data: {}

services:
  annatar:
    build:
      dockerfile: Dockerfile  # Path to your Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - jackett
    volumes:
      - "redis_data:/app/data"
    environment:
      LOG_LEVEL: debug
      JACKETT_URL: "http://82.172.152.9:9117"
      JACKETT_API_KEY: "kptut9ad0fqgllyeykn27dhr9p6cd3hq"
      JACKETT_MAX_RESULTS: "100" # max results from jackett search
      JACKETT_TIMEOUT: "60" # max time spent searching per indexer.
      JACKETT_INDEXERS: "audiences,hdsky,isohunt2,keepfriends,kickasstorrents-to,kickasstorrents-ws,limetorrents,milkie,pterclub,rutracker,rutracker-ru,scenehd,springsunday,thepiratebay,torrentleech,totheglory2fa,yourbittorrent"
      LISTEN_PORT: "8000"

  jackett:
    image: docker.io/linuxserver/jackett
    ports:
      - 9117:9117
    volumes:
      - jackett_config:/config
